apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openstack
nameSuffix: -custom-network

components:
- ../preprovisioned # for baremetal nodes, replace with baremetal

resources:
  - values.yaml

replacements:
# OpenStackDataPlaneNodeSet customizations
- source:
    kind: DataPlaneConfig
    name: edpm-custom-networks-values
    fieldPath: data.nodeset.nodetemplate.ansible.vars.neutron_public_interface_name
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars.neutron_public_interface_name
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-custom-networks-values
    fieldPath: data.nodeset.nodetemplate.ansible.vars.ctlplane_dns_nameservers
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars.ctlplane_dns_nameservers
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-custom-networks-values
    fieldPath: data.nodeset.nodetemplate.ansible.vars.edpm_ovn_dbs
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars.edpm_ovn_dbs
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-custom-networks-values
    fieldPath: data.nodeset.nodetemplate.ansible.vars.edpm_sshd_allowed_ranges
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars.edpm_sshd_allowed_ranges
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-custom-networks-values
    fieldPath: data.nodeset.nodes
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodes
    options:
      create: true
