# This file is for teaching kustomize how to substitute OpenStackDataPlaneService name reference in OpenStackDataPlaneNodeSet
nameReference:
- kind: OpenStackDataPlaneService
  version: v1beta1
  group: dataplane.openstack.org
  fieldSpecs:
  - kind: OpenStackDataPlaneNodeSet
    version: v1beta1
    group: dataplane.openstack.org
    path: spec/services
