# permissions for end users to edit openstackversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstackversion-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/part-of: openstack-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstackversion-editor-role
rules:
- apiGroups:
  - core.openstack.org
  resources:
  - openstackversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackversions/status
  verbs:
  - get
