# permissions for end users to view openstacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstack-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/part-of: openstack-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstack-viewer-role
rules:
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks/status
  verbs:
  - get
