apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role-operator
subjects:
- kind: ServiceAccount
  name: openstack-operator-controller-operator
  namespace: system
