# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackcontrolplanes.core.openstack.org
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: openstack-operators
          name: openstack-operator-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
