apiVersion: core.openstack.org/v1beta1
kind: OpenStackVersion
metadata:
  labels:
    #app.kubernetes.io/name: openstackversionupdate
    #app.kubernetes.io/instance: openstackversionupdate-sample
    #app.kubernetes.io/part-of: openstack-operator
    #app.kubernetes.io/managed-by: kustomize
    #app.kubernetes.io/created-by: openstack-operator
  name: openstack
spec:
  targetVersion: 0.0.2
  openstackControlPlaneName: openstack
