## Append samples you want in your CSV to this file as resources ##
# NOTE(dprince): these get added to the bundle ALM examples
# we do not have space for long examples here and want
# to guide users to documentation instead
resources:
- operator_v1beta1_openstack.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
